name: tim mcgaw
favicon: null
layout_spectrum: 0.6450079816859215
typography_spectrum: 0.14130446803756058
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.2522820960730314
  lightness: 0.8871079829987139
  saturation: 0.8844549907371402
  rhythmicContrast: 0.058126322692260146
purpose: []
